apiVersion: v1
kind: Service
metadata:
  name: logger-load-balancer
  labels:
    app: logger
  namespace: logger
spec:
  type: LoadBalancer
  ports:
  - name: logger-load-balancer
    port: 8086
    targetPort: 80
  selector:
    app: logger